name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x' 

      - name: Build and test
        run: dotnet test test/ClearBank.DeveloperTest.Tests/ClearBank.DeveloperTest.Tests.csproj 
          /p:CollectCoverage=true 
          /p:CoverletOutput=TestResults/ 
          /p:CoverletOutputFormat=lcov
        
      - name: Publish coverage report to coveralls.io
        uses: coverallsapp/github-action@master   
        with:
          github-token: ${{ secrets.CODE_COVERAGE_TOKEN }} 
          path-to-lcov: test/ClearBank.DeveloperTest.Tests/TestResults/coverage.info 
